### ISSUE TITLE
run demo error for com.alibaba.spring.cloud.fescar.config.FescarAutoConfiguration required a bean of type 'org.springframework.web.client.RestTemplate' that could not be found

### ISSUE THREAD

**Issue by xieyeming** [XCXCXCXCX/spring-cloud-fescar#1]
FescarAutoConfiguration class addFescarInterceptor error.
Parameter 0 of method addFescarInterceptor in com.alibaba.spring.cloud.fescar.config.FescarAutoConfiguration required a bean of type 'org.springframework.web.client.RestTemplate' that could not be found.

**Comment by XCXCXCXCX** [comment]
You can avoid this error by injecting the restTemplate yourself, or using the latest code, I have fixed this problem.
